In [1]:
import pandas as pd
import numpy as np
import requests, re
import datetime
import time
from KrakenInterface import KrakenInterface, format_codes_names
from bs4 import BeautifulSoup

ADA   | Cardano
ALGO  | Algorand
ATOM  | Cosmos
BAT   | Basic Attention Token
BCH   | Bitcoin Cash
COMP  | Compound
DAI   | Dai
DASH  | DASH
DOT   | DOT
EOS   | EOS
GNO   | Gnosis
ICX   | ICON
KAVA  | Kava
KNC   | Kyber Network
LINK  | Chainlink
LSK   | Lisk
OMG   | OmiseGO
OXT   | Orchid
PAXG  | PAX Gold
QTUM  | QTUM
SC    | Siacoin
STORJ | Storj
TRX   | Tron
USDT  | Tether
USDC  | USD Coin
WAVE  | Waves
ETC   | Ethereum Classic
ETH   | Ethereum
LTC   | Litecoin
MLN   | Watermelon
REP   | Augur
REPV2 | Augur v2
XBT   | Bitcoin
XDG   | Dogecoin
XLM   | Stellar Lumens
XMR   | Monero
XRP   | Ripple
XTZ   | Tezos
ZEC   | Zcash
CAD   | Canadian dollar
EUR   | Euro
GBP   | Great British Pound
JPY   | Japanese Yen
USD   | US Dollar
KFEE  | Kraken Fee Credits

ETH | Ethereum
XBT | Bitcoin
EUR | Euro
USD | US Dollar

In [2]:
page = open('curr_names.html', 'r').read()
soup = BeautifulSoup(page, "lxml")
table = soup.findAll("td")[4:]
for status in table[3::4][:6]:
    print(status.contents[0])
    print(status.contents[0] == '\xa0')

True

True

True

True

True
<span class='3D"wysiwyg-color-red120"'>delisted</span>
False

In [3]:
codenames = {}
for code, name, status in zip(table[::4], table[1::4], table[3::4]):
    if status.contents[0] == '\xa0':
        if code.span is None:
                codenames[code.contents[0]] = name.contents[0]
        else:
            codenames[code.span.contents[0]] = re.findall("[\w\s]+", name.span.contents[0])[0]
    
#     

codenames

{'ADA': 'Cardano',
 'ALGO': 'Algorand',
 'ATOM': 'Cosmos',
 'BAT': 'Basic Attention Token',
 'BCH': 'Bitcoin Cash',
 'COMP': 'Compound',
 'DAI': 'Dai',
 'DASH': 'DASH',
 'DOT': 'DOT',
 'EOS': 'EOS',
 'GNO': 'Gnosis',
 'ICX': 'ICON',
 'KAVA': 'Kava',
 'KNC': 'Kyber Network',
 'LINK': 'Chainlink',
 'LSK': 'Lisk',
 'OMG': 'OmiseGO',
 'OXT': 'Orchid',
 'PAXG': 'PAX Gold',
 'QTUM': 'QTUM',
 'SC': 'Siacoin',
 'STORJ': 'Storj',
 'TRX': 'Tron',
 'USDT': 'Tether',
 'USDC': 'USD Coin',
 'WAVE': 'Waves',
 'XETC': 'Ethereum Classic',
 'XETH': 'Ethereum',
 'XLTC': 'Litecoin',
 'XMLN': 'Watermelon',
 'XREP': 'Augur',
 'XREPV2': 'Augur v2',
 'XXBT': 'Bitcoin',
 'XXDG': 'Dogecoin',
 'XXLM': 'Stellar Lumens',
 'XXMR': 'Monero',
 'XXRP': 'Ripple',
 'XXTZ': 'Tezos',
 'XZEC': 'Zcash',
 'ZCAD': 'Canadian dollar',
 'ZEUR': 'Euro',
 'ZGBP': 'Great British Pound',
 'ZJPY': 'Japanese Yen',
 'ZUSD': 'US Dollar',
 'KFEE': 'Kraken Fee Credits'}

In [4]:
# codes_clean = ass.code.apply(lambda x: x[1:] if (x[0] == "X")|(x[0] == "Z") else x)

ass = pd.DataFrame(data=codenames.items(), columns=['codes', 'name'])
ass["codes_clean"] = ass.codes.apply(lambda x: x[1:] if (x[0] == "X")|(x[0] == "Z") else x)
ass["fiats"] = ass.codes.apply(lambda x: x[1:] if x[0] == 'Z' else np.nan)
ass["cryptos"] = ass[ass.fiats.isna()]["codes_clean"]


fiat_codes = ass["fiats"].dropna().values
fiat_codes

array(['CAD', 'EUR', 'GBP', 'JPY', 'USD'], dtype=object)

In [5]:
ass["fiats"].dropna().values

array(['CAD', 'EUR', 'GBP', 'JPY', 'USD'], dtype=object)

In [6]:
ass.codes.values

array(['ADA', 'ALGO', 'ATOM', 'BAT', 'BCH', 'COMP', 'DAI', 'DASH', 'DOT',
       'EOS', 'GNO', 'ICX', 'KAVA', 'KNC', 'LINK', 'LSK', 'OMG', 'OXT',
       'PAXG', 'QTUM', 'SC', 'STORJ', 'TRX', 'USDT', 'USDC', 'WAVE',
       'XETC', 'XETH', 'XLTC', 'XMLN', 'XREP', 'XREPV2', 'XXBT', 'XXDG',
       'XXLM', 'XXMR', 'XXRP', 'XXTZ', 'XZEC', 'ZCAD', 'ZEUR', 'ZGBP',
       'ZJPY', 'ZUSD', 'KFEE'], dtype=object)

In [7]:
asset = 'XBT'
fiat = 'EUR'
kr = KrakenInterface()
asks, bids = kr.order_book_of(10)
# rec = requests.get('https://api.kraken.com/0/public/Ticker?pair=XBTeur').json()['result']
asks

         price  volume           timestamp
0  8826.200195   4.506 2020-09-04 21:50:40
1  8827.400391   0.720 2020-09-04 21:50:40
2  8827.700195   0.806 2020-09-04 21:50:40
3  8828.000000   0.099 2020-09-04 21:50:40
4  8828.299805   0.720 2020-09-04 21:50:40
5  8829.500000   2.000 2020-09-04 21:50:40
6  8829.799805   0.287 2020-09-04 21:50:40
7  8830.000000   0.104 2020-09-04 21:50:40
8  8830.099609   0.155 2020-09-04 21:50:40
9  8830.200195   2.389 2020-09-04 21:50:40

In [8]:
kr.asset = 'ETH'
kr.order_book_of(1)[0].price.iloc[-1]

324.87

In [9]:
# s = ''
# for key, val in zip(asset_names.codes.values, asset_names.name.values):
#     s += '{:<4s} | {:s}\n'.format(str(key), str(val))
    
# print(s)

In [10]:
kr.get_asset_pairs()["quote"].unique()

array(['XETH', 'ZEUR', 'ZUSD', 'XXBT', 'ZJPY', 'ZAUD', 'ZGBP', 'USDT',
       'CHF', 'DAI', 'USDC', 'ZCAD'], dtype=object)

In [11]:
kr.get_fiat_pairs()["quote"].unique()

array(['ZEUR', 'ZUSD', 'ZJPY', 'ZGBP', 'ZCAD'], dtype=object)

In [12]:
unknown_ass = "LINK"
kr.get_fiat_pairs().query("@unknown_ass in base")

,altname,wsname,aclass_base,base,aclass_quote,quote,base_clean,quote_clean
LINKEUR,LINKEUR,LINK/EUR,currency,LINK,currency,ZEUR,LINK,EUR
LINKUSD,LINKUSD,LINK/USD,currency,LINK,currency,ZUSD,LINK,USD

In [13]:
asset, currency = "XRP", "EUR"
# asset, currency = "LINK", "USD"
base = 'https://api.kraken.com/0/public/'
market = asset + currency
url = base + 'Depth?pair={}&count={}'.format(market.upper(), 5)

page = requests.get(url)
jString = page.json()
jString

{'error': [],
 'result': {'XXRPZEUR': {'asks': [['0.21403000', '2439.339', 1599245490],
    ['0.21406000', '10000.000', 1599245477],
    ['0.21410000', '31368.139', 1599245493],
    ['0.21411000', '3617.000', 1599245488],
    ['0.21412000', '10000.000', 1599245473]],
   'bids': [['0.21400000', '473.385', 1599245493],
    ['0.21399000', '896.575', 1599245489],
    ['0.21397000', '4682.978', 1599245493],
    ['0.21396000', '5050.000', 1599245491],
    ['0.21395000', '30836.757', 1599245493]]}}}

In [14]:
asset_pairs = kr.get_asset_pairs()
asset_pairs.query("base_clean == @asset & quote_clean == @currency")

,altname,wsname,aclass_base,base,aclass_quote,quote,base_clean,quote_clean
XXRPZEUR,XRPEUR,XRP/EUR,currency,XXRP,currency,ZEUR,XRP,EUR

In [17]:
asset_pairs.query("base_clean == @asset")["quote_clean"].values

array(['AUD', 'ETH', 'GBP', 'USDT', 'XBT', 'CAD', 'EUR', 'JPY', 'USD'],
      dtype=object)

In [18]:
asset_pairs = kr.get_asset_pairs()
valid = asset_pairs.query("base_clean == @asset").quote_clean.values
valid

array(['AUD', 'ETH', 'GBP', 'USDT', 'XBT', 'CAD', 'EUR', 'JPY', 'USD'],
      dtype=object)

In [22]:
# print(format_codes_names(kr.assets))

In [23]:
kr.assets

     codes                   name codes_clean fiats cryptos
0      ADA                Cardano         ADA   NaN     ADA
1     ALGO               Algorand        ALGO   NaN    ALGO
2     ATOM                 Cosmos        ATOM   NaN    ATOM
3      BAT  Basic Attention Token         BAT   NaN     BAT
4      BCH           Bitcoin Cash         BCH   NaN     BCH
5     COMP               Compound        COMP   NaN    COMP
6      DAI                    Dai         DAI   NaN     DAI
7     DASH                   DASH        DASH   NaN    DASH
8      DOT                    DOT         DOT   NaN     DOT
9      EOS                    EOS         EOS   NaN     EOS
10     GNO                 Gnosis         GNO   NaN     GNO
11     ICX                   ICON         ICX   NaN     ICX
12    KAVA                   Kava        KAVA   NaN    KAVA
13     KNC          Kyber Network         KNC   NaN     KNC
14    LINK              Chainlink        LINK   NaN    LINK
15     LSK                   Lisk         LSK   NaN     LSK
16     OMG                OmiseGO         OMG   NaN     OMG
17     OXT                 Orchid         OXT   NaN     OXT
18    PAXG               PAX Gold        PAXG   NaN    PAXG
19    QTUM                   QTUM        QTUM   NaN    QTUM
20      SC                Siacoin          SC   NaN      SC
21   STORJ                  Storj       STORJ   NaN   STORJ
22     TRX                   Tron         TRX   NaN     TRX
23    USDT                 Tether        USDT   NaN    USDT
24    USDC               USD Coin        USDC   NaN    USDC
25    WAVE                  Waves        WAVE   NaN    WAVE
26    XETC       Ethereum Classic         ETC   NaN     ETC
27    XETH               Ethereum         ETH   NaN     ETH
28    XLTC               Litecoin         LTC   NaN     LTC
29    XMLN             Watermelon         MLN   NaN     MLN
30    XREP                  Augur         REP   NaN     REP
31  XREPV2               Augur v2       REPV2   NaN   REPV2
32    XXBT                Bitcoin         XBT   NaN     XBT
33    XXDG               Dogecoin         XDG   NaN     XDG
34    XXLM         Stellar Lumens         XLM   NaN     XLM
35    XXMR                 Monero         XMR   NaN     XMR
36    XXRP                 Ripple         XRP   NaN     XRP
37    XXTZ                  Tezos         XTZ   NaN     XTZ
38    XZEC                  Zcash         ZEC   NaN     ZEC
39    ZCAD        Canadian dollar         CAD   CAD     NaN
40    ZEUR                   Euro         EUR   EUR     NaN
41    ZGBP    Great British Pound         GBP   GBP     NaN
42    ZJPY           Japanese Yen         JPY   JPY     NaN
43    ZUSD              US Dollar         USD   USD     NaN
44    KFEE     Kraken Fee Credits        KFEE   NaN    KFEE

In [ ]:
fiat_pairs = kr.get_fiat_pairs()
valid = fiat_pairs.query("base_clean == @asset")
# valid.quote_clean
valid

In [ ]:
def print_codes_names(df, column):
    s = ''
    max_len = df[column].str.len().max()
    for key, val in zip(df[column].values, df.name.values):
        s += f'{str(key):<{max_len}s} | {str(val):s}\n'
    return s

print(print_codes_names(kr.assets, "codes"))

In [ ]:
fiat_pairs = kr.get_fiat_pairs()
valid = fiat_pairs.query("base_clean == @asset")
# valid.quote_clean
valid

In [ ]:
# fiat_pairs[["base_clean", "quote_clean"]] = fiat_pairs.wsname.str.split("/", expand=True)
# fiat_pairs

In [ ]:
marketS = find_index(asset.upper(), currency.upper())
marketS = '{}{}'.format(asset.upper(), currency.upper())
asks = jString["result"][marketS]["asks"]
bids = jString["result"][marketS]["bids"]

dataAsks = pd.DataFrame(asks, columns=['price', 'volume', 'timestamp'], dtype='float32')
dataBids = pd.DataFrame(bids, columns=['price', 'volume', 'timestamp'], dtype='float32')

dataAsks

In [36]:
kr.fiats[["codes_clean", "name"]].values

array([['CAD', 'Canadian dollar'],
       ['EUR', 'Euro'],
       ['GBP', 'Great British Pound'],
       ['JPY', 'Japanese Yen'],
       ['USD', 'US Dollar']], dtype=object)

In [29]:
kr.fiats.codes_clean.values

array(['CAD', 'EUR', 'GBP', 'JPY', 'USD'], dtype=object)

In [26]:
kr.assets

     codes                   name codes_clean fiats cryptos
0      ADA                Cardano         ADA   NaN     ADA
1     ALGO               Algorand        ALGO   NaN    ALGO
2     ATOM                 Cosmos        ATOM   NaN    ATOM
3      BAT  Basic Attention Token         BAT   NaN     BAT
4      BCH           Bitcoin Cash         BCH   NaN     BCH
5     COMP               Compound        COMP   NaN    COMP
6      DAI                    Dai         DAI   NaN     DAI
7     DASH                   DASH        DASH   NaN    DASH
8      DOT                    DOT         DOT   NaN     DOT
9      EOS                    EOS         EOS   NaN     EOS
10     GNO                 Gnosis         GNO   NaN     GNO
11     ICX                   ICON         ICX   NaN     ICX
12    KAVA                   Kava        KAVA   NaN    KAVA
13     KNC          Kyber Network         KNC   NaN     KNC
14    LINK              Chainlink        LINK   NaN    LINK
15     LSK                   Lisk         LSK   NaN     LSK
16     OMG                OmiseGO         OMG   NaN     OMG
17     OXT                 Orchid         OXT   NaN     OXT
18    PAXG               PAX Gold        PAXG   NaN    PAXG
19    QTUM                   QTUM        QTUM   NaN    QTUM
20      SC                Siacoin          SC   NaN      SC
21   STORJ                  Storj       STORJ   NaN   STORJ
22     TRX                   Tron         TRX   NaN     TRX
23    USDT                 Tether        USDT   NaN    USDT
24    USDC               USD Coin        USDC   NaN    USDC
25    WAVE                  Waves        WAVE   NaN    WAVE
26    XETC       Ethereum Classic         ETC   NaN     ETC
27    XETH               Ethereum         ETH   NaN     ETH
28    XLTC               Litecoin         LTC   NaN     LTC
29    XMLN             Watermelon         MLN   NaN     MLN
30    XREP                  Augur         REP   NaN     REP
31  XREPV2               Augur v2       REPV2   NaN   REPV2
32    XXBT                Bitcoin         XBT   NaN     XBT
33    XXDG               Dogecoin         XDG   NaN     XDG
34    XXLM         Stellar Lumens         XLM   NaN     XLM
35    XXMR                 Monero         XMR   NaN     XMR
36    XXRP                 Ripple         XRP   NaN     XRP
37    XXTZ                  Tezos         XTZ   NaN     XTZ
38    XZEC                  Zcash         ZEC   NaN     ZEC
39    ZCAD        Canadian dollar         CAD   CAD     NaN
40    ZEUR                   Euro         EUR   EUR     NaN
41    ZGBP    Great British Pound         GBP   GBP     NaN
42    ZJPY           Japanese Yen         JPY   JPY     NaN
43    ZUSD              US Dollar         USD   USD     NaN
44    KFEE     Kraken Fee Credits        KFEE   NaN    KFEE

In [ ]:
fiat_pairs.base.isin(kr.fiats.codes)

In [ ]:
kr.fiat_codes

In [ ]:
codes_clean.values

In [ ]:
allpairs

In [ ]:
allpairs = kr.get_asset_pairs()
allpairs.query("@ass.codes.values not in base")

In [ ]:
pd.set_option("display.max_rows", 50, "display.max_columns", 10)
allpairs[allpairs.base.isin(codes_clean)]

In [ ]:
# page = open(r'curr_names.html', 'r').read()
# soup = BeautifulSoup(page, "html")
# tbody = str(soup.find('tbody'))

In [ ]:
# url = 'https://api.kraken.com/0/public/AssetPairs'
# page = requests.get(url)
# jString = page.json()
# jString

In [ ]:
# allpairs = jString["result"].keys()
# allpairs
# # [i for i in allpairs if "EUR" in i]

In [ ]:
fiatnames = ass[ass.codes.str.startswith('Z')]
fiatnames

In [ ]:
asset_names = re.findall('<tr>\n<td class="confluenceTd">(\w*)</td>\n<td class="confluenceTd">(.*)</td>', tbody)
asset_names = pd.DataFrame(asset_names, columns=['codes', 'name'])
fiatnames = asset_names[asset_names.codes.isin(fiats)]
codes_clean = asset_names.codes.apply(lambda x: x[1:] if (x[0] == "X")|(x[0] == "Z") else x)
# asset_names.codes = codes_clean
asset_names[asset_names.codes.str.startswith('Z')]
# .sort_values('codes')
fiatnames

In [ ]:
fiats = fiatnames.codes.values 
fiats

In [ ]:
fiatmask = allpairs['quote'].isin(fiats)
fiatpairs = allpairs[fiatmask]
fiatpairs

In [ ]:
cryptofiat = fiatpairs.base.unique()
cryptofiat

In [ ]:
cryptofiat

In [ ]:
asset_names[asset_names.codes.isin(cryptofiat)]

In [ ]:
allpairs.quote.unique()

In [ ]:
allpairs[allpairs.base == 'XXBT']